# Site settings
title:        Finding Baseline of Google Fonts
description:  >
  Baseline Ratio Database of Google Fonts.
  The baseline ratio of fonts can be used for sass mixins
  or css to build baseline grid and vertical rhythm.
baseurl:      /finding-baseline
url:          https://designmeme.github.io
author:       Jihye Lee
email:        ghe.lee19@gmail.com
logo:         /assets/image/brand/symbole.jpg # og_image

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/image/brand/logo.jpg # og_image

# Custom vars
google_analytics: UA-93339811-1
favicon_version: 1.1.1
paypal: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=AKTGBZD4YZWGG&lc=GA&item_name=designmeme&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted

# Build settings
permalink:        pretty
timezone:         GMT
exclude:
  - assets/scss
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - README.md
  - node_modules
  - vendor
gems:
  - jekyll-sitemap